### PR TITLE
Fix single block blob download

### LINKED ISSUE #280: [BUG] UX Study. Download transfers that complete with only one block do not automatically switch to .complete
Identified in the UX study. If a download requires only 1 block (< 4MB) then the state does not trigger identifying the transfer as complete.

### PR DESCRIPTION
**Pull request by tjprescott**
Fixes #280.

### CODE REVIEW

File: sdk/storage/AzureStorageBlob/Source/Operation/BlobDownloadOperations.swift [hunk 1]
```diff
@@ -53,7 +53,10 @@ internal class BlobDownloadInitialOperation: TransferOperation {
         }
 
         // early out if no more blocks are necesasry
-        guard downloader.blockList.count > 0 else { return }
+        guard downloader.blockList.count > 0 else {
+            transfer.state = .complete
```
Comment (tjprescott) [inline sdk/storage/AzureStorageBlob/Source/Operation/BlobDownloadOperations.swift:57]: This was the cause of the problem.

Comment (bsiegel) [reply sdk/storage/AzureStorageBlob/Source/Operation/BlobDownloadOperations.swift:57]: Well that was easy. 👍
