### PR TITLE
Fix MD5 hashing and restore to true

### LINKED ISSUE #248: MD5 hashing enabled yields EXC_BAD_ACCESS
Workaround was to turn this feature off temporarily.

### PR DESCRIPTION
**Pull request by tjprescott**
Fixes #248.  I think the actual `EXC_BAD_ACCESS` was fixed by an earlier PR. This simply tweaks previously merged changes that caused turning the option on to yield a 400 error.

### CODE REVIEW

File: sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift [hunk 1]
```diff
@@ -47,7 +47,7 @@ public struct StorageBlobClientOptions: AzureConfigurable {
     public init(
         apiVersion: String = StorageBlobClient.ApiVersion.latest.rawValue,
         logger: ClientLogger = ClientLoggers.default(tag: "StorageBlobClient"),
-        maxChunkSize: Int = 4 * 1024 * 1024
+        maxChunkSize: Int = 4 * 1024 * 1024 - 1
```
Comment (tjprescott) [inline sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift:50]: Above this value, you will get a 400 error.

File: sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift [hunk 2]
```diff
@@ -160,12 +160,16 @@ internal class ChunkDownloader {
...
         if let rangeGetContentMD5 = options.range?.calculateMD5 {
             headers[.rangeGetContentMD5] = String(rangeGetContentMD5)
+            headers[.range] = "bytes=\(startRange)-\(endRange)"
         }
         if let rangeGetContentCRC64 = options.range?.calculateCRC64 {
             headers[.rangeGetContentCRC64] = String(rangeGetContentCRC64)
+            headers[.range] = "bytes=\(startRange)-\(endRange)"
+        }
+        if headers[.range] == nil {
+            headers[.xmsRange] = "bytes=\(startRange)-\(endRange)"
```
Comment (tjprescott) [inline sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift:172]: To use the hashing functions you must use `.range`, not `.xmsRange` or you'll get a 400 error.

File: sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift (hunk 1 above)
Comment (bsiegel) [reply sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift:50]: Oh, we should definitely document that in the parameter comment. We should also validate this in the StorageBlobClient initializer and throw an exception (since those initializers are already marked as throwing).

File: sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift (hunk 2 above)
Comment (bsiegel) [reply sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift:172]: Is it safe to just use `range` all the time? The API docs state:
> If the x-ms-range header is specified on a request, then the service uses the range specified by x-ms-range; otherwise, the range specified by the Range header is used.

Comment (tjprescott) [reply sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift:172]: Since you changed it to x-ms-range in your PR, I assumed there was some case for it so I kept that. But when requesting hashes, you _must_ use Range.

File: sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift (hunk 1 above)
Comment (tjprescott) [reply sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift:50]: I added the parameter comment, but adding the validation in the SDK was always an anti-pattern in CLI. If the Storage service were updated to allow hashes greater than this limit, we would be artificially restricting the user. The requirements to use hashing are clearly spelled out in the REST API docs:
https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob#request-headers

File: sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift (hunk 2 above)
Comment (bsiegel) [reply sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift:172]: Oh, no I just realized that we had `HTTPHeaders.range = "Range"` and `StorageHTTPHeaders.range = "x-ms-range"`, I simply renamed the enum value for the second to `.xmsRange` so that places where it was used didn't need to qualify the value.

File: sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift (hunk 1 above)
Comment (bsiegel) [reply sdk/storage/AzureStorageBlob/Source/DataStructures/StorageBlobClientOptions.swift:51]: OH, I see it's only a limitation for requests that use hashing. Yep, what you wrote makes perfect sense.

File: sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift (hunk 2 above)
Comment (tjprescott) [reply sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift]: I didn't see any issues when I set both headers to the same value, so I went with that. Let me know what you think.

Comment (bsiegel) [reply sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift]: It's a small thing so I don't think it matters, but I guess for simplicity's sake if we can just use Range, I'd prefer that. Probably just so that coming back to this code later, someone (maybe me :p) doesn't look at it and ask "okay why are we setting both headers to the same value??".

Comment (tjprescott) [reply sdk/storage/AzureStorageBlob/Source/StorageStreamDownloader.swift]: Updated.
